services:
  prometheus:
    image: prom/prometheus:v2.49.0-rc.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
      - '--enable-feature=promql-experimental-functions'
      - '--log.level=debug'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - 127.0.0.1:9091:9091
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    user: root
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - ./grafana.db:/var/lib/grafana/grafana.db
volumes:
  prom_data:
